version: '3.7'

x-env-php: &env-php
  PHP_VERSION: 7.4.19

x-env-mysql: &env-mysql
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

x-env-initdata: &env-initdata
  SUPERUSER_NAME: ${SUPERUSER_NAME}
  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
  WORKSPACE_NAME: ${WORKSPACE_NAME}


services:
  testcenter-db-backend:
    image: mysql:5.7
    container_name: testcenter-db-backend
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "9091:3306"

  testcenter-backend:
    container_name: testcenter-backend-standalone
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        <<: *env-php
    environment:
      <<: *env-mysql
      <<: *env-initdata
      MYSQL_HOST: testcenter-db-backend
      MYSQL_PORT: 3306
    depends_on:
      - testcenter-db-backend
    volumes:
      - ../classes:/var/www/html/classes
      - ../definitions:/var/www/html/definitions
      - ../docs/specs.yml:/var/www/html/docs/specs.yml
      - ../routes:/var/www/html/routes
      - ../sampledata:/var/www/html/sampledata
      - ../vo_data:/var/www/html/vo_data
      - ../vendor:/var/www/html/vendor
      - ../composer.json:/var/www/html/composer.json
      - ../composer.lock:/var/www/html/composer.lock
    ports:
      - "9092:80"


volumes:
  db_data:
